#PreCommit:
#  RuboCop:
#    enabled: true
#    on_warn: fail # Treat all warnings as failures
#
#  TrailingWhitespace:
#    exclude:
#      - '**/db/structure.sql' # Ignore trailing whitespace in generated files
#
#PostCheckout:
#  ALL: # Special hook name that customizes all hooks of this type
#    quiet: true # Change all post-checkout hooks to only display output on failure
#
#  IndexTags:
#    enabled: true # Generate a tags file with `ctags` each time HEAD changes

PreCommit:
  # Style Check
  RuboCop:
    enabled: true
    command: ['bundle', 'exec', 'rubocop', '-c', './.rubocop.yml']
    on_warn: fail

  # Security Check
  Brakeman:
    enabled: true
    command: ['bundle', 'exec', 'brakeman']
    on_warn: fail

  # Style Check in HAML
  HamlLint:
    enabled: true
    on_warn: fail

  # YAML Check
  YamlSyntax:
    enabled: true
    on_warn: fail

  # Dependency Check
  BundleCheck:
    enabled: true
    on_warn: fail

  # Migration Check
  RailsSchemaUpToDate:
    enabled: true
    on_warn: fail

  # Checks for hard tabs in files
  HardTabs:
    enabled: true
    on_warn: fail

PrePush:
    # Unit & Integration TEST
  RSpec:
    enabled: true
    command: ['bundle', 'exec', 'rspec', 'spec']
    on_warn: fail

  BundleInstall:
    enabled: true
    on_warn: fail